### ISSUE TITLE
feature: build syncer binary with behavior customized for edge-mc

### ISSUE THREAD

**Issue by waltforme** [kcp-dev/edge-mc#163]
### Feature Description

We need the syncer's behavior to be customized for the edge use cases.

### Proposed Solution

The kcp community has [agreed](https://github.com/kcp-dev/kcp/issues/2682#issuecomment-1422051212) to introduce command line flag(s) of the syncer into kcp-dev/kcp. We can then make use of the flag(s) to build syncer binary for edge-mc.

### Want to contribute?

- [x] I would like to work on this issue.

**Comment by andreyod** [comment]
If I understand correctly the [agreed ](https://github.com/kcp-dev/kcp/issues/2682#issuecomment-1422051212)approach  here is to maintain EMC syncer binary as an opposite to introducing command line flag of the syncer into kcp-dev/kcp.
So the fastest way would be to copy related parts of syncer code into EMC(while sharing as much code as possible) and change the behavior to connect to the apiserver in the pcluster.

**Comment by ezrasilvera** [comment]
@andreyod I agree. It seems that we only need to copy & change the syncer mutator. This will allow us to avoid any change in the KCP code (and minimal change in the edge-mc mutator copy) , while being able to have two different syncer binaries as requested.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer What do you think?   This seems like a cleaner approach than, for example, adding a conditional attribute the shared syncer mutator and exposing it through all functions to the different syncer main(s)

**Comment by andreyod** [comment]
> It seems that we only need to copy & change the syncer mutator.

The change will be in mutators package bat we may need to copy other files that import mutators package.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer there are two issues with adding such support into the KCP code:

1. It requires changes in all the calling function stack (they are passing single parameters rather than a structure) . This seems like a redundant effort as KCP doesn't seem like going to use this feature in the near future
2. Are we sure that we won't need to have edge specific functionality in pkg/syncer - which will require us to for these files in any case. 

Let me ask David again. I just wanted to understand what is your preference.

**Comment by clubanderson** [comment]
@mra-ruiz would you like to get involved in this conversation?

**Comment by waltforme** [comment]
We now have an edge syncer independent from kcp syncer. Closing.
