### ISSUE TITLE
bug: Non public document linked in cmd/placement/README.md

### ISSUE THREAD

**Issue by francostellari** [kcp-dev/edge-mc#172]
### Describe the bug

The link https://docs.google.com/document/d/1AzyjuyjNIDVAXEGHslaggltIQ9Cs8pLCzc9Ma_RBmuM/edit#heading=h.vmt32rdidje6 referenced in https://github.com/kcp-dev/edge-mc/blob/main/cmd/placement/README.md is not publicly accessible

### Steps To Reproduce

1. Go to https://github.com/kcp-dev/edge-mc/blob/main/cmd/placement/README.md 
2. Click on the [document](https://docs.google.com/document/d/1AzyjuyjNIDVAXEGHslaggltIQ9Cs8pLCzc9Ma_RBmuM/edit#heading=h.vmt32rdidje6) link
3. Document is not publicly accessible

### Expected Behaviour

Google document should open without requiring user to request permission

**Comment by waltforme** [comment]
Thanks @francostellari !

This will be fixed by #161 because in #161 we are refactoring the controller so that it will not refer to the document any more.

But the document itself sounds to be public anyway. IDK why.
<img width="215" alt="image" src="https://user-images.githubusercontent.com/8633434/218877753-ae36333c-549b-4f8f-988d-531e5fd1b767.png">
