### ISSUE TITLE
bug: docs need more clarity on versions

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#231]
### Describe the bug

1. https://github.com/kcp-dev/edge-mc/blob/main/CONTRIBUTING.md#prerequisites says "Go 1.19+", which could reasonably be interpreted to include go release 1.20.  But https://github.com/kcp-dev/edge-mc/blob/main/hack/verify-go-versions.sh insists on exactly the major.minor listed in `go.mod`.
2. It should be clearly stated, in a way that contributors come across quickly, that there is a dependency on a specific version of kcp and what that version is or how to find it.

### Steps To Reproduce

See above

### Expected Behaviour

More clarity.

**Comment by pdettori** [comment]
Seems like we inherited the "Go 1.19+" from https://docs.kcp.io/kcp/main/en/CONTRIBUTING/ - perhaps we should open an issue on kcp core as well ?

**Comment by clubanderson** [comment]
@fileppb can you work this to closure please?  Seems straightforward.  Might involve opening an issue with kcp project as part of the resolution.

**Comment by fileppb** [comment]
@MikeSpreitzer @pdettori Are you just asking for a clarification to the documentation, or are you looking for a better implementation of the kcp/hack/verify-go-versions.sh? I think the script itself is inflexible since it only allows for go version 1.x using VERSION=$(grep "go 1." go.mod | sed 's/go //'). I think it would be more flexible to do this: VERSION=$(grep "go [0-9][.]" go.mod | sed 's/go //'). And then the documentation should also be changed to say that the tags in the kcp yamls should identically match the go version in go.mod's "go" directive.

**Comment by fileppb** [comment]
@clubanderson I opened this as an issue with kcp: https://github.com/kcp-dev/kcp/issues/2904

**Comment by MikeSpreitzer** [comment]
@fileppb : Re 1: the ask is only to make the documentation clearer.
That has been done.  Thanks!

Item 2 remains (we have defocused on contributors lately).

**Comment by pdettori** [comment]
I think this can be closed
