### ISSUE TITLE
bug: issues in KCP-Edge Syncer doc

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#294]
### Describe the bug

This issue concerns https://docs.kcp-edge.io/docs/coding-milestones/poc2023q1/edge-syncer/ .

1. The picture at the top shows an `APIExport` in the WMW, but I do not understand why that should be so.  There is an APIExport of the edge.kcp.io group in the ESPW.  In the WMW the custom resources should be defined by CRDs rather than APIBindings, since APIBindings do not work in the edge clusters.
2. In the "Registering Edge Syncer on a p-cluster" section, step 2 has a command line command shown but there is no explanation of exactly  what this command does.  Also, it is odd that this step says to run that command with the current workspace set to the mailbox workspace; users should not need to do anything to that workspace (apart from covering for the gap in mailbox controller functionality).

### Steps To Reproduce

See above.

### Expected Behaviour

No confusion.

**Comment by yana1205** [comment]
As for 2, I created the PR: https://github.com/kcp-dev/edge-mc/pull/299 that describes the detail of `kcp workload edge-sync` command and the equivalent manual steps.

**Comment by yana1205** [comment]
As for 1, I create the PR: https://github.com/kcp-dev/edge-mc/pull/306 that removes descriptions about APIExport from pictures since we don't use APIExport/APIBinding pattern but will go with Mailbox informer to collect upsynced resources from mailbox workspaces. There are other fixes included following up yesterday's internal communication. (rename pcluster to edge cluster, mention SyncerConfig, correct some wording)
