### ISSUE TITLE
bug: kubestellar command insists that docker be running

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#441]
### Describe the bug

The `kubestellar` command insists that `docker ps` work.  But that is not logical, KubeStellar does not require Docker to be running locally.

### Steps To Reproduce

Invoke `kubestellar start` without Docker running locally.

### Expected Behaviour

No unnecessary checking.

**Comment by clubanderson** [comment]
without docker running I could not run the quickstart.  You need to download a container, and for that you need docker running.  This issue should be marked invalid unless you decouple the download of the syncer container from the quickstart - which I do not think we can do because it is necessary at this time.

**Comment by clubanderson** [comment]
Don't we do a docker pull of the syncer during QS workflow?

**Comment by MikeSpreitzer** [comment]
Not so far as I can tell.

**Comment by clubanderson** [comment]
How (where) do we pull the docker image for syncer?

**Comment by clubanderson** [comment]
resolved with 'requirements' at the beginning of each doc.  The automation in the doc is now installing and starting docker as needed.
