### ISSUE TITLE
bug: the placement-translator docs are failing due to the placement translator - no mappings are showing up

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/edge-mc#557]
### Describe the bug

see https://github.com/kcp-dev/edge-mc/actions/runs/5172188324/jobs/9316294417#step:6:10945 and the output directly after this line.  You will see that the placement translator is not working as expected in the demo.  I have no doubt that the placement translator works as part of the quickstart directions, but I do not see it working as part of the placement-translator.md directions

### Steps To Reproduce

run through the directions in the placement-translator.md docs.  While in the root:espw the command "kubectl get workspace" yields nothing. 

### Expected Behavior

The instructions in the placement-translator.md should work end-to-end

### Additional Context

search for '++' from the bottom up to see the commands that are being run. You can certainly start from the top and work downward, but you will see the commands from the run-doc-shells script before you see the commands from the placement-translator.md being executed.

**Comment by MikeSpreitzer** [comment]
The edits to make this document executable were incomplete.  Some of the older text is not consistent with the latest bash commands.  Some of that is merely confusing, such as where the text says "It is also assumed that you have the usual kcp kubectl plugins on your `$PATH`." but the bash commands take care of making that so (thus, it is NOT assumed, and actually NOT EXPECTED).  More importantly, see how the text keeps referring the reader to the example?  Some of that is critical and not covered by the bash commands.  The reader is expected to create some workload and EdgePlacement objects.

FYI, here is a relevant and surprising feature of kcp's APIExport/APIBinding functionality: when a client requests a list all of objects of an exported kind, before any such objects are ever created, the request is rejected with a complaint about the server not knowing about the requested resource.  That is what is happening here.  Because the bash commands do not make any edge EdgePlacement objects, all the controllers are being told there the server does not know about that kind of object, and are not prceeding to do anything else (such as make SinglePlacementSlice objects or mailbox workspaces).

**Comment by clubanderson** [comment]
you can hide the commands that run through the CI by using the instructions at https://docs.kubestellar.io/main/Contribution%20guidelines/operations/document-management/.  Check out the section on codeblocks and running/testing documentation below that.

**Comment by clubanderson** [comment]
is this still an issue?  if so, can you point to the specific document and location within the document where you are seeing this?

**Comment by MikeSpreitzer** [comment]
@clubanderson , you opened this issue.  If I understand correctly, it has been resolved.

**Comment by clubanderson** [comment]
resolved
